algoritmo "par ou impa"
// Função :  iforma se o numero digitado e par ou impa
// Autor : Ronald Pinheiro
// Data : 18/06/2022
// Seção de Declarações 
var
   num : inteiro
inicio
// Seção de Comandos
      Escreva("Digite um número:")
      leia(num)
      Se (num%2 = 0) entao
      Escreval("O número ",num," é par")
      senao
      Escreval("O número ", num, " é impa")
      fimse
fimalgoritmo
