algoritmo "semnome"
// Função : mostrar atribuição e leitura de dados em um vetor
// Autor : boson_Treinamento
// Data : 20/04/2013
// Seção de Declarações
// Aula_18: Vetores- Atribuição de valores e leitura de dados
var
    minhanota: real
    notas: vetor[0..9] de real
inicio
// Seção de Comandos
       notas[0] <- 8.5
       minhanota <- notas[0]
       escreval("A variável contém: ",minhanota)
       escreval("O vetor, na posição de indice 0 contém: ",notas[0])
       
fimalgoritmo
