algoritmo "Operadores_Relacionais"
// Função :mostrar como funcinan os operdaores lógicos
// Autor : Boson_treinamento
// Data : 01/04/2013
// Seção de Declarações 
// aula_8 : Operadores e expresões Relacionais
var
   a, b : inteiro

inicio
// Seção de Comandos
       a <- 7
       b<- 9
       escreval(a <= (b-1))
       Escreval( a >= b)
       Escreval( a = b)
       escreval ( a <> b)
fimalgoritmo
