algoritmo "Somar_dois_Números"
// Função : Demostrar a soma de dois números
// Autor : Bonson_Treinamento
// Data : 01/04/2013
// Seção de Declarações 
// Ala_7: Comando de Entrada e Saída de dados
var
     x,y, z: inteiro
inicio
// Seção de Comandos
     Escreval("Digite o primeiro número e pressione ENTER: ")
     leia(x)
     Escreval("Digite outro número e pressione ENTER")
     leia(y)
     z <- x + y
     Escreval("O resultado da soma é:", z)
fimalgoritmo

